[package]
name = "itest"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = []
# Do not add features here that are 1:1 forwarded to the `godot` crate.
# Instead, compile itest with `--features godot/my-feature`.

[dependencies]
godot = { path = "../../godot", default-features = false }

[build-dependencies]
godot-bindings = { path = "../../godot-bindings" } # emit_godot_version_cfg
quote = "1"
proc-macro2 = "1"
